-- src/Structures/S01_BooleanCore/Step01_BooleanFoundation.agda
{-# OPTIONS --safe #-}

-- | Step 01: Boolean Core
-- | Purpose: Construct Bool as the minimal algebra of distinction,
-- |          derived from D₀ (First Difference).
-- | Method: Define Bool as a datatype with two constructors,
-- |         corresponding to the two faces of D₀.

module Structures.S01_BooleanCore.Step01_BooleanFoundation where

open import Agda.Primitive using (Level; lzero)
open import Core.TokenPrinciple

-- | Bool as the *first algebra* generated by D₀
--   Two tokens = two sides of the First Difference.
data Bool : Set where
  true  : Bool
  false : Bool

-- | Negation as involution
not : Bool → Bool
not true  = false
not false = true

-- | Conjunction (∧)
_∧_ : Bool → Bool → Bool
true  ∧ y = y
false ∧ y = false

-- | Disjunction (∨)
_∨_ : Bool → Bool → Bool
true  ∨ y = true
false ∨ y = y
